.TH "WebApplication7.Models.Phone" 3 "Mon Apr 4 2022" "WebApplication7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebApplication7.Models.Phone \- Definitions for the \fBPhone\fP table  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBIDPhone\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCPFCustomer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsPrivate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBNamePhone\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPhoneNumber\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBCustomer\fP \fBCustomer\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definitions for the \fBPhone\fP table 

.SH "Author"
.PP 
Generated automatically by Doxygen for WebApplication7 from the source code\&.
