.TH "WebApplication7.RouteConfig" 3 "Mon Apr 4 2022" "WebApplication7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebApplication7.RouteConfig
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterRoutes\fP (RouteCollection routes)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WebApplication7 from the source code\&.
