.TH "WebApplication7.Models.Address" 3 "Mon Apr 4 2022" "WebApplication7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebApplication7.Models.Address \- Definitions for the \fBAddress\fP table  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBIDAddress\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCPFCustomer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCountry\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMoreInfo\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBNameAddress\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBNumber\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPostalCode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBRegion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBStreet\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBCustomer\fP \fBCustomer\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definitions for the \fBAddress\fP table 

.SH "Author"
.PP 
Generated automatically by Doxygen for WebApplication7 from the source code\&.
