.TH "WebApplication7.MvcApplication" 3 "Mon Apr 4 2022" "WebApplication7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebApplication7.MvcApplication
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Web\&.HttpApplication\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBApplication_Start\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WebApplication7 from the source code\&.
