.TH "WebApplication7.FilterConfig" 3 "Mon Apr 4 2022" "WebApplication7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebApplication7.FilterConfig
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterGlobalFilters\fP (GlobalFilterCollection filters)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WebApplication7 from the source code\&.
