.TH "WebApplication7.Models" 3 "Mon Apr 4 2022" "WebApplication7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebApplication7.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddress\fP"
.br
.RI "Definitions for the \fBAddress\fP table "
.ti -1c
.RI "class \fBCustomer\fP"
.br
.RI "Definitions for the \fBCustomer\fP table "
.ti -1c
.RI "class \fBModel1\fP"
.br
.RI "Entity Framework context "
.ti -1c
.RI "class \fBPhone\fP"
.br
.RI "Definitions for the \fBPhone\fP table "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WebApplication7 from the source code\&.
