.TH "WebApplication7.Controllers" 3 "Mon Apr 4 2022" "WebApplication7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebApplication7.Controllers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddressesController\fP"
.br
.RI "Controller for manipulations in table Address "
.ti -1c
.RI "class \fBCustomersController\fP"
.br
.RI "Controller for manipulations in table Customers "
.ti -1c
.RI "class \fBPhonesController\fP"
.br
.RI "Controller for manipulations in table Phone "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WebApplication7 from the source code\&.
